backend:
  name: git-gateway
  branch: main

media_folder: assets/img/uploads/

# collections:
#   - name: "settings"
#     label: "Site Settings"
#     files:  # Path to your settings file
#       file: "_data/sitesettings.yml"
#       fields:
# - label: "Colors"
#   name: "colors"
#   widget: "object"
#   fields:
#     - { label: "Primary Color", name: "clr_primary", widget: "color" }
#     - { label: "Secondary Color", name: "clr_secondary", widget: "color" }
#     - {
#         label: "Secondary Hover Color",
#         name: "clr_secondary_hover",
#         widget: "color",
#       }
#     - { label: "Hero Text Color", name: "clr_hero_text", widget: "color" }
#     - { label: "Button Color", name: "clr_btn", widget: "color" }
#     - { label: "Background Color", name: "bg_color", widget: "color" }
#     - {
#         label: "Concerts Background Color",
#         name: "clr_bg_concerts",
#         widget: "color",
#       }
#     - { label: "Text Color", name: "text_color", widget: "color" }
#     - {
#         label: "Hamburger Background Color",
#         name: "hamburger_bg_color",
#         widget: "color",
#       }
collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/_data/sitesettings.yml"
        label: "Settings1"
        name: "settings1"
        fields:
          - label: "Test"
            name: "test"
            widget: "string"
          - label: "Button Color"
            name: "clr_btn"
            widget: "color"
            default: "#ffffff"
          - label: "Background Color"
            name: "bg_color"
            widget: "color"
            default: "#ffffff"
          - label: "Primary Color"
            name: "clr_primary"
            widget: "color"
            default: "rgb(190, 146, 64)"
          - label: "Text Color"
            name: "text_color"
            widget: "color"
            default: "rgba(0, 0, 0, 0.85)"
          - label: "Concerts Background Color"
            name: "clr_bg_concerts"
            widget: "color"
            default: "aliceblue"
          - label: "Secondary Hover Color"
            name: "clr_secondary_hover"
            widget: "color"
            default: "rgba(99, 136, 161, 0.85)"
          - label: "Hero Text Color"
            name: "clr_hero_text"
            widget: "color"
            default: "#ffffff"
          - label: "Secondary Color"
            name: "clr_secondary"
            widget: "color"
            default: "rgba(99, 136, 161, 1)"
          - label: "Hamburger Background Color"
            name: "hamburger_bg_color"
            widget: "color"
            default: "#ffffff"
