clr_primary: "#be9240"
clr_secondary: "#6388a1"
text_color: rgba(0, 0, 0, 0.85)
bg_color: "#ffffff"
clr_btn: "#00213e"
clr_bg_concerts: "#070718"
bg_color_rgb: 255,255,255
clr_secondary_hover: rgba(99, 136, 161, 0.85)
clr_hero_text: "#ffffff"
hamburger_bg_color: "#ffffff"
