clr_primary: "#563c13"
clr_secondary: "#51791a"
text_color: rgba(151, 91, 91, 0.85)
bg_color: white
clr_btn: white
clr_bg_concerts: "#f5f7f9"
clr_secondary_hover: rgba(99, 136, 161, 0.85)
clr_hero_text: "#ffffff"
hamburger_bg_color: "#ffffff"
