clr_primary: "#c59635"
clr_secondary: "#22739c"
text_color: rgba(255, 255, 255, 0.85)
bg_color: "#0b1a25"
clr_btn: "#00213e"
clr_bg_concerts: "#183750"
bg_color_rgb: 255,255,255
clr_secondary_hover: rgba(99, 136, 161, 0.85)
clr_hero_text: "#ffffff"
hamburger_bg_color: "#ffffff"
