clr_primary: "#d4af37"
clr_secondary: "#43b3c9"
text_color: rgba(255, 255, 255, 0.85)
bg_color: "#0d1f2d"
clr_btn: "#00213e"
clr_bg_concerts: "#1b1c1d"
bg_color_rgb: 255,255,255
clr_secondary_hover: rgba(99, 136, 161, 0.85)
clr_hero_text: "#ffffff"
hamburger_bg_color: "#ffffff"
