# site-settings.yml

# Color Settings
colors:
  clr_primary: "rgb(190, 146, 64)" # Formerly --clr-primary
  clr_secondary: "rgba(99, 136, 161, 1)" # Formerly --clr-secondary
  clr_secondary_hover: "rgba(99, 136, 161, 0.85)" # Formerly --clr-secondary-hover
  clr_hero_text: white;
  clr_btn: white
  bg_color: "white"
  # bg_color_rgb: "255, 0, 0" # Formerly --bg-color
  clr_bg_concerts: aliceblue;
  text_color: "rgba(0, 0, 0, 0.85)" # Formerly --text-color
  hamburger_bg_color: white;
  gradient: "linear-gradient(212deg, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 93%)"

hero:
  focus:
    options:
      - left
      - right
      - center
  photo_focus: center
  text_alignment: 70%
  arrow: false
  bottomborder: false

# Font Settings
# Font Settings
fonts:
  options:
    - "Roboto"
    - "Playfair Display"
    - "Montserrat"
    - "Lora"
    - "Open Sans"
    - "Raleway"
    - "Merriweather"
    - "Poppins"
    - "Oswald"
    - "Nunito"
    - "Work Sans"
    - "Rubik"
    - "Lato"
    - "Josefin Sans"
    - "Fira Sans"
    - "Quicksand"
    - "Source Sans Pro"
    - "PT Sans"
  primary_font: "Montserrat" # Default primary font
  secondary_font: "Playfair Display" # Default secondary font

buttons:
  border_radius: "50px"

borders:
  border_size: 10px;
  color:
    options:
      - "var(--clr-primary)"
      - "var(--clr-secondary)"
  border_color: "var(--clr-secondary)"
# Spacing & Layout
spacing:
  section_padding: "2em"
  container_width: "1200px"

# Shadows and Effects
effects:
  box_shadow: "rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px"
# Daan's Settings
# colors:
#   clr_primary: "rgb(190, 146, 64)" # Formerly --clr-primary
#   clr_secondary: "rgba(99, 136, 161, 1)" # Formerly --clr-secondary
#   clr_secondary_hover: "rgba(99, 136, 161, 0.85)" # Formerly --clr-secondary-hover
#   bg_color: "rgb(255, 255, 255)" # Formerly --bg-color
#   text_color: "rgba(0, 0, 0, 0.85)" # Formerly --text-color
#   gradient: "linear-gradient(212deg, rgb(255, 255, 255) 0%, rgb(255, 255, 255) 93%)"
