test: Hij doet het!!
colors:
  clr_btn: white
  bg_color: white
  clr_primary: "#79551c"
  text_color: rgba(80, 6, 6, 0.85)
  clr_bg_concerts: aliceblue;
  clr_secondary_hover: rgba(99, 136, 161, 0.85)
  clr_hero_text: white;
  clr_secondary: "#51791a"
  hamburger_bg_color: white;
hero:
  focus:
    options:
      - left
      - right
      - center
  photo_focus: center
  text_alignment: 70%
  arrow: false
  bottomborder: false
fonts:
  options:
    - Roboto
    - Playfair Display
    - Montserrat
    - Lora
    - Open Sans
    - Raleway
    - Merriweather
    - Poppins
    - Oswald
    - Nunito
    - Work Sans
    - Rubik
    - Lato
    - Josefin Sans
    - Fira Sans
    - Quicksand
    - Source Sans Pro
    - PT Sans
  primary_font: Montserrat
  secondary_font: Playfair Display
buttons:
  border_radius: 50px
borders:
  border_size: 10px;
  color:
    options:
      - var(--clr-primary)
      - var(--clr-secondary)
  border_color: var(--clr-secondary)
spacing:
  section_padding: 2em
  container_width: 1200px
effects:
  box_shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px
