borders:
  border_size: 10px;
  color:
    options:
      - var(--clr-primary)
      - var(--clr-secondary)
  border_color: var(--clr-secondary)
spacing:
  section_padding: 2em
  container_width: 1200px
effects:
  box_shadow: rgba(0, 0, 0.3) 0px 1px 2px 0px, rgba(0, 0, 0, 0.15) 0px 2px 6px 2px
